---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t=eu.gcr.io/$PROJECT_ID/retailer-api-documentation:pr$_PR_NUMBER-$SHORT_SHA
      - --cache-from=eu.gcr.io/$PROJECT_ID/retailer-api-documentation:latest
      - .
